package com.spring.gst.util;

import com.spring.gst.model.ResponseObject;
import com.spring.gst.model.User;

public class ResponseUserUtil {

	public static ResponseObject createResponseUser()
	{
		ResponseObject response = new ResponseObject();
		response.setSuccess("true");
		response.setToken("JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyIkX18iOnsic3RyaWN0TW9kZSI6dHJ1ZSwic2VsZWN0ZWQiOnt9LCJnZXR0ZXJzIjp7fSwiX2lkIjoiNTk1YmE4NDAxYTQxNzEwM2ZjNGE1ZGY5Iiwid2FzUG9wdWxhdGVkIjpmYWxzZSwiYWN0aXZlUGF0aHMiOnsicGF0aHMiOnsicGFzc3dvcmQiOiJpbml0IiwidXNlcm5hbWUiOiJpbml0IiwiZW1haWwiOiJpbml0IiwiX192IjoiaW5pdCIsIm5hbWUiOiJpbml0IiwiX2lkIjoiaW5pdCJ9LCJzdGF0ZXMiOnsiaWdub3JlIjp7fSwiZGVmYXVsdCI6e30sImluaXQiOnsiX192Ijp0cnVlLCJwYXNzd29yZCI6dHJ1ZSwidXNlcm5hbWUiOnRydWUsImVtYWlsIjp0cnVlLCJuYW1lIjp0cnVlLCJfaWQiOnRydWV9LCJtb2RpZnkiOnt9LCJyZXF1aXJlIjp7fX0sInN0YXRlTmFtZXMiOlsicmVxdWlyZSIsIm1vZGlmeSIsImluaXQiLCJkZWZhdWx0IiwiaWdub3JlIl19LCJwYXRoc1RvU2NvcGVzIjp7fSwiZW1pdHRlciI6eyJkb21haW4iOm51bGwsIl9ldmVudHMiOnt9LCJfZXZlbnRzQ291bnQiOjAsIl9tYXhMaXN0ZW5lcnMiOjB9fSwiaXNOZXciOmZhbHNlLCJfZG9jIjp7Il9fdiI6MCwicGFzc3dvcmQiOiIkMmEkMTAkeHBjbmUzQjFGU1Viemt2c2RzdE5UT3NtRDBiZFQ1VXBOOXFTYTBCZjdLbWRuVGN2WUZIMTIiLCJ1c2VybmFtZSI6InZpdmVrIiwiZW1haWwiOiJ2aXZla3ZhcmRoYW4uc0BnbWFpbC5jb20iLCJuYW1lIjoiVml2ZWsgUmVkZHkiLCJfaWQiOiI1OTViYTg0MDFhNDE3MTAzZmM0YTVkZjkifSwiJGluaXQiOnRydWUsImlhdCI6MTUwMDk3MzY0MCwiZXhwIjoxNTAxNTc4NDQwfQ.GzjZDrq-UtdPTkI-7YH-DrfLV5p46SiXFbFfY5E4IHI");
		User user = new User("595ba8401a417103fc4a5df9","Vivek Reddy","vivek","vivekvardhan.s@gmail.com");
		response.setUser(user);
		
		return response;
	}
}

